### ISSUE TITLE
New frontend - First and second last names order

### ISSUE THREAD

**Issue by aureliomexa** [davlum/poet#17]
As they are now, first and second last name are in the incorrect order. These examples show how it should be.

Where it says:
Aurelio Valdez Meza
Leika Quesnel Mochán
Salvador De León Tercero 
Juan José Infante Casasús Díaz

It should say:
Aurelio Meza Valdez
Leika Mochán Quesnel 
Salvador Tercero De León 
Juan José Díaz Infante Casasús

**Comment by aureliomexa** [comment]
Following up on this. Is it possible to make?

**Comment by davlum** [comment]
It's possible ish, basically full names are inserted into the single name column instead of having multiple like before, I must have been inserted them in the wrong order. I can split the names by spaces and reorder the second and third name, but it would apply to all names. Good for this solution?

**Comment by aureliomexa** [comment]
There are actually not too many cases with two last names, so we are changing them manually.

**Comment by davlum** [comment]
Alright, then I'll close this issue.
