### ISSUE TITLE
Can't listen to new uploaded MP3 files

### ISSUE THREAD

**Issue by aureliomexa** [davlum/poet#19]
We can't listen to the MP3 students have been uploading, check this for example: https://poeticasonora.me/obra/432 . If you try to open it from the back-end, you get a 403 Error.

**Comment by poeticasonora** [comment]
The 403 Error happens with the most recently uploaded recordings, the first 24 to appear on the recordings database, according to this screenshot. 
![Screenshot_2019-03-03 Seleccione Grabación a modificar Sitio de administración de Django](https://user-images.githubusercontent.com/48571725/54577426-6eec3380-49c1-11e9-9065-9feeb080c68d.png)
It should be noted that the last 8 recordings, i.e. "Fauna Ciudad de México", "Vagos en una esquina blanca", "Fiesta", "Ciudad puente", "Vynil", "Menundencias" and "Señora Lexotan" have been published, while the rest remain unplublished or pending publication. However, if we click on the file of one of the pending recordings, for example, "Primavera en el fondo del colon" we also get the 403 error message, as shown in these screenshots.
![Screenshot_2019-03-18 Modificar Grabación Sitio de administración de Django](https://user-images.githubusercontent.com/48571725/54577687-66482d00-49c2-11e9-92d5-1007d0725ffa.png)
![Screenshot_2019-03-18 403 Forbidden](https://user-images.githubusercontent.com/48571725/54577700-72cc8580-49c2-11e9-8383-6d7be06f3ba9.png)
