### ISSUE TITLE
500 Error on entity-to-recording relation: feedback from Juan Carlos

### ISSUE THREAD

**Issue by aureliomexa** [davlum/poet#20]
Juan Carlos is a grad student doing an internship with us. Here's a couple requests he sent us:
"I'm still getting the 500 Error when I tried to add an entity-to-recording relation, for example from entity 'Guillermo Galindo' to 'Dormía cuando entró a mi cuarto'. This has happened with all the entities and by pressing any of the three 'Save' buttons. Another comment about this issue is the difficulty to find both recordings and entities; given that there is a very long list of every recording and entity, it is complicated to find what you need. Even though typing the first letters of a name can make it easier to query, it is problematic when there are many entities with the same name; for example, finding Guillermo Galindo is particularly complicated. Maybe we can list it in alphabetical order or add any other filter, like the ones we had before." #

**Comment by poeticasonora** [comment]
The 500 error persists when trying to save new roles. For instance, we tried to add the "Contribuidor" role to Poetica Sonora Mx and the "publicador" role to Suzanna Molina, in relation to the recording "Así era ella", as shown below
![thumbnail_image](https://user-images.githubusercontent.com/48571725/55516466-84509700-562a-11e9-8697-6e7b554c63e5.png)
but when we clicked on the "save" button, the 500 error page followed
![thumbnail_image(1)](https://user-images.githubusercontent.com/48571725/55516538-b3ff9f00-562a-11e9-9aca-6ba6fd946d1b.png)
