### ISSUE TITLE
"Ninguno" bug

### ISSUE THREAD

**Issue by aureliomexa** [davlum/poet#38]
In a collection's list of interpreters (for example, [this one](https://poeticasonora.me/coleccion/406)), some roles appear as "Ninguno," maybe referring to "lectura en voz alta." I wonder if this list is necessary at all, since interpreters may vary in some collections (not this one, but for example in anthologies or series curated by invited artists).

**Comment by aureliomexa** [comment]
I was looking at the example I quoted last time, and "Ninguno" refers to field Instrumento. It seems that in these cases such information did not survive the refactoring. Does this mean we will have to manually change these cases back to their original values?

**Comment by davlum** [comment]
Looks like you're correct. Here's the output from a quick query on the database. 
```
pojo=# select from_entity, to_work, relationship, instrument from poet_entity_to_work_rel where from_entity = 48;
 from_entity | to_work |      relationship      |     instrument
-------------+---------+------------------------+--------------------
          48 |     368 | Interpretación musical | Ninguno
          48 |     369 | Interpretación musical | Ninguno
          48 |     296 | Lectura en voz alta    | Ninguno
          48 |     307 | Lectura en voz alta    | Ninguno
          48 |     309 | Interpretación musical | Guitarra eléctrica
          48 |     310 | Interpretación musical | Guitarra acústica
          48 |     310 | Lectura en voz alta    | Ninguno
          48 |     311 | Interpretación musical | Guitarra eléctrica
          48 |     343 | Interpretación musical | Ninguno
          48 |     345 | Interpretación musical | Ninguno
          48 |     348 | Interpretación musical | Guitarra eléctrica
          48 |     350 | Interpretación musical | Guitarra acústica
          48 |     352 | Interpretación musical | Ninguno
          48 |     353 | Interpretación musical | Ninguno
          48 |     363 | Interpretación musical | Ninguno
          48 |     364 | Interpretación musical | Ninguno
          48 |     365 | Interpretación musical | Ninguno
          48 |     366 | Interpretación musical | Ninguno
          48 |     367 | Interpretación musical | Ninguno
```

Users shouldn't be able to have `relationship = Interpretación musical` and `instrument = Ninguno` so something went awry in the database migration. Unfortunately because new data has been added to the database we'd be unable to redo those migrations, so yeah, looks like this will have to be handled manually.
