### ISSUE TITLE
Change information display in collection templates

### ISSUE THREAD

**Issue by aureliomexa** [davlum/poet#39]
Information on top of each Collection page is confusing and distributed in a weird way (at least when using a desktop or laptop computer), with the comments displayed on the far right side of the screen, making it difficult to read or nagivate.
Due to the situation reported in issue #38, where not all interpreters or composers may be in all the recordings of a collection, I suggest that the Compositores and Intérpretes lists be removed, and the comments section changed to where Compositores is now (see attached image).
![Modify collection display](https://user-images.githubusercontent.com/40276446/58107367-4514e000-7baf-11e9-9f36-8174d1919406.png)

**Comment by davlum** [comment]
Is this change still wanted?

**Comment by aureliomexa** [comment]
Yes.

**Comment by davlum** [comment]
what would you think about having everything centered and in this order?

1. Album image
2. Comments

And then optionally:

3. Composers
4. Interpreters

I feel like if the composers and interpreters are left out a lot of the interlinking is lost.

**Comment by aureliomexa** [comment]
Okay, that works.
