### ISSUE TITLE
New recordings and entities can't be added due to security issue

### ISSUE THREAD

**Issue by aureliomexa** [davlum/poet#44]
A user-tester in Spain tried to upload two new recordings, but after waiting for a while, she got an error message warning about the site's security configuration. She was granted superuser status to see if that was the problem, but she got the same message. She then sent the Admin these files (one in MP3 format and one in M4A), who also tried to upload them having the same result. Attached is a screenshot and translation of the error:

> Failed secure connection
> The connection to the server was restarted while the page was loading.
>      The page you are trying to view can not be displayed because the authenticity of the received data can not be verified.
>      Please contact the website owners to inform them of this problem.

It is still possible to edit existing objects without any problems. Trying to add a new entity gives a 500 error message. No problems detected while adding and deleting new collections, entity-to-entity and recording-to-entity relationships. 

![add new work bug](https://user-images.githubusercontent.com/40276446/59111380-87a41f80-8906-11e9-96ff-235424039c33.png)

**Comment by davlum** [comment]
The issue was that the webserver and gunicorn threads were timing out on large file (>100M). The max file size and timeout has been adjusted, though it is encouraged to keep file size smaller.
