### ISSUE TITLE
User-tester can't log in or reset her password

### ISSUE THREAD

**Issue by aureliomexa** [davlum/poet#49]
User-tester "Muriel" attempted to log in and could not do it (we're confirming if she used the nickname we assigned her or if she used her email address instead). While attempting to reset her password, she did not get a confirmation email and probably did not have it changed. Here is her report:

> I'm trying to upload the missing recordings to the repository but it oddly says my user information is incorrect. That is very strange to me, because those are the email address and password I always used to log in, they were even stored on my computer. I clicked on the "Forgot Password" link to get an email and retrieve it, but I didn't get any. I don't know if it is a website issue or my profile was deleted.

**Comment by aureliomexa** [comment]
Seems like it was the wrong nickname after all. In order for users not to have any problem reseting their password, I suggest making it mandatory to add an email address when creating a new profile. Here is the report from coordinator Miriam:

> Muchas gracias, Aurelio. Ayer o más bien hoy en la madrugada le contesté a Muriel y le explicaba que con el refactoring del RDA no se conservaron las credenciales de acceso que usamos en el primer prototipo. Y le reenvié sus credenciales actuales.En efecto su nombre de usuario es Muriel y su contraseña es la misma que le asigné cuando creé su perfil. Yo acabo de acceder con estos datos sin mayor problema.
> Me imagino que la función de restaurar contraseña no funcionó porque para crear perfiles en este prototipo no es 100% necesario ingresar una cuenta de correo (?). En el panel de usuarios sólo aparacen tu mail y el de David, pero los demás no tenemos nuestros correos registrados... Supongo que por eso la función para recuperar contraseñas no reconoció el correo de Muriel y por lo mismo no le llegó ningún mensaje para la recuperación.

**Comment by davlum** [comment]
> Seems like it was the wrong nickname after all.

I don't want to force emails on users if they don't want to provide them. If you add an email, you get the additional password reset niceties.
