### ISSUE TITLE
500 error while adding or updating data

### ISSUE THREAD

**Issue by aureliomexa** [davlum/poet#52]
Possibly related to Issue #45. A user-tester was trying to upload new recordings. When she finished filling out the "Agregar grabación" form, she got a 500 error. Then she tried to add a description and an external URL to recording #324 and once again got a 500 error. Both her student coordinator and supervisor tried to add her description and URL and we all got a 500 error.

**Comment by davlum** [comment]
Reopening until confirmed fixed.

**Comment by aureliomexa** [comment]
New files can be uploaded now. The problem is with long files--apparently more than 35 minutes is already too large. They may be uploaded once, but editing their metadata has proved to be difficult, if not impossible.

**Comment by davlum** [comment]
This is a performance issue which can't really be resolved unless a more powerful server is allocated. I suggest keeping the files shorter for the time being.
